### ISSUE TITLE
Targets for a multiplatform library 

### ISSUE THREAD

**Issue by briancroom** [samdmarshall/QandA#4]
You led off your article on "Using Xcode Targets" by pointing out the challenges posed by the four separate platforms that Xcode is now capable of building for. Do any of the techniques described in your post provide an alternative to using separate targets for Mac/iOS/watchOS/tvOS if I am trying to producing a dynamic framework usable by apps on any Apple platform?

Thanks!

**Comment by samdmarshall** [comment]
Yes, the only fundamental different between different platform targets is the SDK that you supply for it. The compiler settings, target requirements (like required signing on iOS vs not required on OS X) is entirely dictated by the platform and SDK that is selected. You can alter the target platform and SDK by altering the `SDKROOT` build setting for the target. There may be some additional differences that might need to be satisfied, such as the Info.plist, but all of those can specified through the build settings for the target.

One thing i mention in the post that makes this a bit tricky is that while you can use a single target for multiple platforms, you need to also alter the `PRODUCT_NAME` per platform if you want to have an accompanying test target that works. This is because the test target uses the `TEST_HOST` build setting to resolve the built product via string matching (ew). To make the test target work for the multi-platform target you need to alter the `PRODUCT_NAME` per platform and make sure the `TEST_HOST` matches that new name. The easiest way to do this is via shared xcconfig files. 

I am hoping to make another post soon that goes into depth on how to migrate all your build settings safely from the xcodeproj over to xcconfig files in further detail, but this should be able to get you started.
