### ISSUE TITLE
Bundle IDs in Xcode 8 iOS provisioning for enterprise and developer accounts

### ISSUE THREAD

**Issue by tsackett** [samdmarshall/QandA#8]
Your amazing blog post on migrating to Xcode 8 signing (https://pewpewthespells.com/blog/migrating_code_signing.html) includes information on configuring a project so it could be built with both app store and enterprise provisioning. However, if these are in two different developer accounts, doesn't the bundle ID have to be different? I didn't see how to do this in the instructions you provided.

**Comment by samdmarshall** [comment]
Sorry about that, part of the post assumed certain things about your setup; one of which was the management of the bundle identifier through the build settings panel or via xcconfigs to customize the value of `PRODUCT_BUNDLE_IDENTIFIER` based on if you were building locally vs enterprise deployment vs app store distribution. Hope this clears that up for you.

**Comment by tsackett** [comment]
I think I understand better after your comment. I'm a release engineer working with a development team. I don't normally work in Xcode myself, but I need to define a set of requirements for how the devs set up the projects, so that the automated build system can sign correctly. I'll do some experiments in a sample app to see if I can work this out. Thanks

**Comment by samdmarshall** [comment]
I would strongly recommend that this entirely gets managed by the developers within the Xcode Build System. They should be creating at least 3 shared schemes for the project/workspace:

1. Building the app in local development mode (this is going to be used by the developers for day-to-day work)
2. Building the app for enterprise deployment (this will be built by CI for QA)
3. Building the app for App Store distribution (this will be built by CI to prevent developers having access to the private signing keys for the App Store builds)

Once configured, these three configurations shouldn't have to be modified again. Configurations 2 and 3 will be run on CI and because they are managed by the developers (who then relay the credentials or signing details to you) all you will have to worry about is calling `xcodebuild` for the specific scheme in the desired build configuration. The iOS developers should understand enough of my blog post to setup the configurations and xcconfig files necessary to do this. If they need some more help then there are a number of other posts on my blog that can provide them with the necessary information.
